[package]
name = "incremental-methods"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "incremental_methods"
path = "src/lib.rs"

[build-dependencies]
risc0-build = { version = "2.1.0", features = ["unstable"] }

[package.metadata.risc0]
methods = ["guest"]

